### ISSUE TITLE
How can I access the Container inside the authentication method

### ISSUE THREAD

**Issue by Dimonina** [msmolka/ZNetCS.AspNetCore.Authentication.Basic#1]
Hi. I'm curious of how I can check the username and password against the database. I want to get my database context from the container, but I don't understand how I can access IServiceProvider inside the OnValidatePrincipal method

**Comment by msmolka** [comment]
Hello
`OnValidatePrincipal` method as parameter provides `ValidatePrincipalContext`. This context provides `UserName`, `Password` and `HttpContex`. From `HttpContext` there is access to registered services and dependency injection e.g. To EF Core DB Context.
```csharp

    OnValidatePrincipal = async (context) =>
    {
        var dbContext = context.HttpContext.RequestServices.GetRequiredService<Context>();
        var user = await dbContext.Users.Where(u => u.LoginName == context.UserName && u.Password == context.Password).SingleOrDefaultAsync();
        if (user != null)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, context.UserName, context.Options.ClaimsIssuer)
            };

            var ticket = new AuthenticationTicket(
                new ClaimsPrincipal(new ClaimsIdentity(claims, BasicAuthenticationDefaults.AuthenticationScheme)),
                new Microsoft.AspNetCore.Authentication.AuthenticationProperties(),
                BasicAuthenticationDefaults.AuthenticationScheme);

            return AuthenticateResult.Success(ticket);
        }

        return AuthenticateResult.Fail("Authentication failed.");
    }

```

**Comment by mattosaurus** [comment]
Hi @msmolka, what exactly is "Context" in the below line of code?

`var dbContext = context.HttpContext.RequestServices.GetRequiredService<Context>();`

I'd assumed it was actually meant to be "HttpContext" but dbContext then doesn't have a "Users" property. Intellisense suggests it should be "Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context" but this again doesn't have a "Users" property

Thanks

Matt

**Comment by msmolka** [comment]
@mattosaurus In this case it is EF Core DBContext. Your DB access.
