### ISSUE TITLE
AuthorizeAttribute

### ISSUE THREAD

**Issue by reft** [msmolka/ZNetCS.AspNetCore.Authentication.Basic#10]
Hi,

Would it be possible to use this as an attribute instead of a global filter e.g.

    [Route("[controller]")]
    [ApiController]
    public class TestController : ControllerBase
    {
        [HttpGet]
        [ZNetCS.BasicAuthorize]
        public IActionResult Get()
        {

I just want to use this for one controller and have the rest use jwt authentication as default, (I would rather not use policies).

**Comment by msmolka** [comment]
But you can, define basic authentication with given scheme name. And then use e.g.[Authorize(AuthenticationSchemes = BasicAuthenticationDefaults.AuthenticationScheme)]

**Comment by reft** [comment]
purrfect thank you
