### ISSUE TITLE
AuthenticationFailMessage not written to body

### ISSUE THREAD

**Issue by francesconi** [msmolka/ZNetCS.AspNetCore.Authentication.Basic#11]
Shouldn't the `AuthenticationFailMessage` be added to the response body in case of authentication failure? I've also found no test which covers this usecase.

**Comment by msmolka** [comment]
`AuthenticationFailMessage` is added as `AuthenticateResult.Fail(` message. Because `Fail` allows to provide message, I’ve added possibility to provide such message when `Principal` is null. Rest is done through the authentication framework and handled in generic way.
