### ISSUE TITLE
This is not working in .net core 3

### ISSUE THREAD

**Issue by sandeshmm** [msmolka/ZNetCS.AspNetCore.Authentication.Basic#13]
It is working fine in .net core 2.2 but not in .net core 3.  This is not showing any error but no user name and password popup is displaying in new .net version.

**Comment by msmolka** [comment]
what is your startup?

**Comment by sandeshmm** [comment]
this is working old startup

 public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });


            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

            services.AddDbContext<WallContext>(options => options.UseSqlServer(Configuration.GetConnectionString("WallDatabase")));

            services.AddScoped<IDataService, DataService>();

            services.AddSession();

            services
       .AddAuthentication(BasicAuthenticationDefaults.AuthenticationScheme)
       .AddBasicAuthentication(
           options =>
           {
               options.Realm = "Wall";
               options.AjaxRequestOptions.SuppressWwwAuthenticateHeader = true;
               options.Events = new BasicAuthenticationEvents
               {
                   OnValidatePrincipal = context =>
                   {

                       var dataService = services.BuildServiceProvider().GetService<IDataService>();

                       if (dataService.ValidateUser(context.UserName, context.Password))
                       {
                           var claims = new List<Claim>
                           {
                                new Claim(ClaimTypes.Name, context.UserName, context.Options.ClaimsIssuer)
                           };

                           var principal = new ClaimsPrincipal(new ClaimsIdentity(claims, BasicAuthenticationDefaults.AuthenticationScheme));
                           context.Principal = principal;
                           Thread.CurrentPrincipal = principal;
                       }
                       else
                       {
                            // optional with following default.
                            context.AuthenticationFailMessage = "Authentication failed."; 
                        }

                       return Task.CompletedTask;
                   }
               };
           });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();

            app.UseSession(); 

            // default authentication initialization
            app.UseAuthentication();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }

    }

**Comment by sandeshmm** [comment]
looks like there is no issues with startup. Same is working fine with core 2.2,  even i created new project with mvc core 3.1 but there also not working.

**Comment by sandeshmm** [comment]
this is new updated startup for core 3

 public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddControllersWithViews();

            services.AddRazorPages();

            services.AddDbContext<WallContext>(options => options.UseSqlServer(Configuration.GetConnectionString("WallDatabase")));

            services.AddScoped<IDataService, DataService>();

            services.AddSession();

            services
       .AddAuthentication(BasicAuthenticationDefaults.AuthenticationScheme)
       .AddBasicAuthentication(
           options =>
           {
               options.Realm = "Wall";
               options.AjaxRequestOptions.SuppressWwwAuthenticateHeader = true;
               options.Events = new BasicAuthenticationEvents
               {
                   OnValidatePrincipal = context =>
                   {

                       var dataService = services.BuildServiceProvider().GetService<IDataService>();

                       if (dataService.ValidateUser(context.UserName, context.Password))
                       {
                           var claims = new List<Claim>
                           {
                                     new Claim(ClaimTypes.Name, context.UserName, context.Options.ClaimsIssuer)
                           };

                           var principal = new ClaimsPrincipal(new ClaimsIdentity(claims, BasicAuthenticationDefaults.AuthenticationScheme));
                           context.Principal = principal;
                           Thread.CurrentPrincipal = principal;
                       }
                       else
                       {
                                // optional with following default.
                                context.AuthenticationFailMessage = "Authentication failed.";
                       }

                       return Task.CompletedTask;
                   }
               };
           });




        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseAuthorization();
            app.UseAuthentication();
            app.UseStaticFiles();
          
            app.UseSession();

            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapControllerRoute(
                            name: "default",
                            pattern: "{controller=Home}/{action=Index}/{id?}");
            });

        }

    }

**Comment by msmolka** [comment]
you have wrong `Configure` section:
see:
https://docs.microsoft.com/en-Us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#migrate-startupconfigure

```
General advice:
    Add UseRouting.

    If the app calls UseStaticFiles, place UseStaticFiles before UseRouting.

    If the app uses authentication/authorization features such as AuthorizePage or [Authorize], place the call to UseAuthentication and UseAuthorization: after, UseRouting and UseCors, but before UseEndpoints
```

**Comment by YishaiHornbacher** [comment]
I'm having the same issue. If I use controllers and endpoints without MVC it works. But as soon as I add MVC, it is not actually authorizing.

**Comment by YishaiHornbacher** [comment]
The resolution appears to be this:

https://stackoverflow.com/a/50526720/77779

UseMvc must be after Use Authorization. In @sandeshmm in your case, maybe put UseRouting before UseAuthentication.

**Comment by MarcoGiorgi** [comment]
In .NET Core 3.1 does not yet work for me. I get always 401 Unauthorized.
This is my startup.cs:

```
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddAuthentication(BasicAuthenticationDefaults.AuthenticationScheme)
                .AddBasicAuthentication(
                  options =>
                  {
                      options.Realm = "My Application";
                      options.Events = new BasicAuthenticationEvents
                      {
                          OnValidatePrincipal = context =>
                          {
                              if ((context.UserName.ToLower() == "usr") && (context.Password == "pwd"))
                              {
                                  var claims = new List<Claim>{
                                                new Claim(ClaimTypes.Name,
                                                            context.UserName,
                                                            context.Options.ClaimsIssuer)
                                    };

                                  var ticket = new AuthenticationTicket(
                                    new ClaimsPrincipal(new ClaimsIdentity(
                                      claims,
                                      BasicAuthenticationDefaults.AuthenticationScheme)),
                                    new Microsoft.AspNetCore.Authentication.AuthenticationProperties(),
                                    BasicAuthenticationDefaults.AuthenticationScheme);

                                  return Task.FromResult(AuthenticateResult.Success(ticket));
                              }

                              return Task.FromResult(AuthenticateResult.Fail("Authentication failed."));
                          }
                      };
                  });

            services.AddMvcCore();
            services.AddApiVersioning(
                                options =>
                                {
                                    options.ReportApiVersions = true;
                                });
            services.AddVersionedApiExplorer(
                options =>
                {
                    options.GroupNameFormat = "'v'VVV";
                    options.SubstituteApiVersionInUrl = true;
                });
            services.AddTransient<IConfigureOptions<SwaggerGenOptions>, ConfigureSwaggerOptions>();
            services.AddSwaggerGen(
                options =>
                {
                    options.OperationFilter<SwaggerDefaultValues>();
                    options.IncludeXmlComments(XmlCommentsFilePath);
                });

            services.AddCors(options =>
            {
                options.AddPolicy(name: "AllowAllOrigins",
                                  builder =>
                                  {
                                      builder.AllowAnyOrigin();
                                  });
            });

            services.AddControllers(options =>
            {
                options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(Point)));
                options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(Coordinate)));
                options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(LineString)));
                options.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(MultiLineString)));
            }).AddNewtonsoftJson(options =>
            {
                foreach (var converter in NetTopologySuite.IO.GeoJsonSerializer.Create(new GeometryFactory(new PrecisionModel(), 4326)).Converters)
                {
                    options.SerializerSettings.NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore;
                    options.SerializerSettings.Converters.Add(converter);
                }
            }).SetCompatibilityVersion(CompatibilityVersion.Version_3_0);

        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IApiVersionDescriptionProvider provider)
        {
            app.UseForwardedHeaders();
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseStaticFiles(new StaticFileOptions
            {
                FileProvider = new PhysicalFileProvider(
                 Path.Combine(Directory.GetCurrentDirectory(), "swagger-ui")),
                RequestPath = "/swagger-ui"
            });

            app.UseHttpsRedirection();
            app.UseRouting();
            app.UseCors("AllowAllOrigins");

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            app.UseSwagger();
            app.UseSwaggerUI(
                options =>
                {
                    // build a swagger endpoint for each discovered API version
                    foreach (var description in provider.ApiVersionDescriptions)
                    {
                        options.SwaggerEndpoint($"/swagger/{description.GroupName}/swagger.json", description.GroupName.ToUpperInvariant());
                    }
                });

        }
        static string XmlCommentsFilePath
        {
            get
            {
                var basePath = PlatformServices.Default.Application.ApplicationBasePath;
                var fileName = typeof(Startup).GetTypeInfo().Assembly.GetName().Name + ".xml";
                return Path.Combine(basePath, fileName);
            }
        }
    }
```

**Comment by msmolka** [comment]
@MarcoGiorgi this is not 3+ config look at docs
https://github.com/msmolka/ZNetCS.AspNetCore.Authentication.Basic#important-change-in-300
