### ISSUE TITLE
Provide a strong name signed NuGet package

### ISSUE THREAD

**Issue by Octoate** [msmolka/ZNetCS.AspNetCore.Authentication.Basic#14]
Hi,
I am trying to use the NuGet package in a signed application, but since the NuGet package is not strong name signed, I cannot use it without signing it by myself, which makes the build process more complicated. It would be great if you could provide a strong name signed NuGet package.

Best regards,
Tim

**Comment by msmolka** [comment]
Done in  05ac92c

**Comment by Octoate** [comment]
Thanks 👍 !
