### ISSUE TITLE
Version compatible with latest ASPNetCore

### ISSUE THREAD

**Issue by mindobjects** [msmolka/ZNetCS.AspNetCore.Authentication.Basic#16]
Here the code necessary to add to program.cs (instead of startup.cs in latest version).

Please add following code in program.cs

```
using System.Security.Claims;
using ZNetCS.AspNetCore.Authentication.Basic;
using ZNetCS.AspNetCore.Authentication.Basic.Events;
```
and

```
builder.Services.AddAuthentication(BasicAuthenticationDefaults.AuthenticationScheme)
                .AddBasicAuthentication(
                    options =>
                    {
                        options.Realm = "Your application";                    
                        options.Events = new BasicAuthenticationEvents
                        {
                            OnValidatePrincipal = context =>
                            {
                                if ((context.UserName == "userName") && (context.Password == "password"))
                                {
                                    var claims = new List<Claim>
                                    {
                                        new Claim(ClaimTypes.Name, context.UserName, context.Options.ClaimsIssuer)
                                    };

                                    var principal = new ClaimsPrincipal(new ClaimsIdentity(claims, context.Scheme.Name));
                                    context.Principal = principal;
                                }
                                else
                                {
                                    // optional with following default.
                                    // context.AuthenticationFailMessage = "Authentication failed."; 
                                }

                                return Task.CompletedTask;
                            }
                        };
                    });

```
in the concerned web page (.cshtml) please add (on top) :
 
```
@using Microsoft.AspNetCore.Authorization
@attribute [Authorize]
```

Thanks for all your works !

**Comment by msmolka** [comment]
Hello
Could you elaborate a bit more the issue?
You are asking about updating documentation?

I don't have upgraded system yet to support .net 6. That's why I'm asking what is not working?

**Comment by mindobjects** [comment]
Hi,

Yes it's an update of the documentation.
In order to works, there is no more startup.cs class.
You have to integrate in program.cs (as describe) and add code inside (cshtml) page to define witch are protected or not.

Do you have any tips for managing disconnection, from now it look like the credentials exist for few time inside the same session (this not append in the Incognito mode of the web browser). Is there any special option that can be used for this (free the credential when the page closed) ?

Thanks.

**Comment by msmolka** [comment]
Thanks for letting me know, I will review .NET 6 later, when back.

About maintaining authentication it is browser thing not code. Browser decides how long keep it:
see: https://stackoverflow.com/a/233551/1164761

**Comment by msmolka** [comment]
Done
