### ISSUE TITLE
Does not support injected BasicAuthenticationEvents

### ISSUE THREAD

**Issue by marcrocny** [msmolka/ZNetCS.AspNetCore.Authentication.Basic#4]
As an alternative to setting `OnValidatePrincipal` directly, it should be possible to inherit `BasicAuthenticationEvents` and override `ValidatePrincipal()`, register the new events-type in `Startup.ConfigureSerivces()` and set it on `AuthenticationSchemeOptions.EventsType`. The security infrastructure will inject it to `AuthenticationHandler.Events` when the sheme's `AuthenticationHandler` is resolved by dependency injection ([see here](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L96)).  

However, `BasicAuthenticationHandler` short-circuits this functionality by calling [`this.Options.Events.ValidatePrincipal(context)`](https://github.com/msmolka/ZNetCS.AspNetCore.Authentication.Basic/blob/master/src/ZNetCS.AspNetCore.Authentication.Basic/BasicAuthenticationHandler.cs#L134). It should be just `Events.ValidatePrincipal(context)`.

**Comment by msmolka** [comment]
Fixed in v3.0.0
