### ISSUE TITLE
Getting 404 rather than 401

### ISSUE THREAD

**Issue by ErynManela** [msmolka/ZNetCS.AspNetCore.Authentication.Basic#5]
I'm attempting to use this but getting 404 Not Found's in dotnet 2.0 MVC rather than 401 Unauthorized's, when I run a unit test on my base endpoint with invalid credentials. - is htis an issue with your code or something I am doing wrong?

I'm using the Dependency injection pattern as follows
```c#
public class AuthenticationEvents: BasicAuthenticationEvents
    {
        private readonly Dictionary<string,string> _basicAuthDictionary = new Dictionary<string, string>
        {
            {"username","password"},
   
        };
        
        #region Public Methods
        /// <inheritdoc/>
        public override Task ValidatePrincipalAsync(ValidatePrincipalContext context)
        {
            
            if (_basicAuthDictionary.Keys.Contains(context.UserName) && context.Password.Equals(_basicAuthDictionary.GetValueOrDefault(context.UserName)))
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, context.UserName, context.Options.ClaimsIssuer)
                };

                var principal = new ClaimsPrincipal(new ClaimsIdentity(claims, BasicAuthenticationDefaults.AuthenticationScheme));
                context.Principal = principal;
                context.AuthenticationFailMessage = null;
            }
            return Task.CompletedTask;
        }
    }
    #endregion
```

In startup.cs I add the services as follows:
```c#    
       public void ConfigureServices(IServiceCollection services)
        {
            services.AddScoped<AuthenticationEvents>();

            services
                .AddAuthentication(BasicAuthenticationDefaults.AuthenticationScheme)
                .AddBasicAuthentication(
                    options =>
                    {
                        options.Realm = "OverDrive.Orator.API";
                        options.EventsType = typeof(AuthenticationEvents);
                    });
```

my controller is as follows:

```c#
[Authorize]
    public class HomeController: Controller
    {
        [Route("")]
        public ActionResult SiteRoot()
        {
            return new ContentResult
            {
                Content = JsonConvert.SerializeObject(new
                {
                    Version = "1.0",
                    Text = "This is a test."
                }),
                ContentType = "application/json"
            };
        }
```

and I have an xunit test that fails:
```
        [Fact]
        public async Task IncorrectAuthFails()
        {
            var username = "foo";
            var password = "INVALIDPASSWORD";
                
            // Act
            var request = new HttpRequestMessage()
            {
                RequestUri = new Uri("https://localhost:4430/"),
                Method = HttpMethod.Get    
            };
            request.Headers.Add("Scheme","https");
            string svcCredentials = Convert.ToBase64String(ASCIIEncoding.ASCII.GetBytes(username + ":" + password));

            request.Headers.Add("Authorization", "Basic " + svcCredentials);
            var response = await _client.SendAsync(request);
            var wwwAuth = response.Headers.WwwAuthenticate.Single();
            var nvh = NameValueHeaderValue.Parse(wwwAuth.Parameter);
            
            Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode);
}
```

**Comment by msmolka** [comment]
I believe something is wrong with you unit tests
This is authorization, so it can only respone authorized or not. 
`404` means your controller is not reached

You can prove it by removing `[Authorize]` attribute.

It is difficult to find out which part is wrong, without seeing whole code. I would look into `TestServer` `WebHostBuilder` part.

**Comment by ErynManela** [comment]
If I put in the actual creds, I get a 200 as if it works.

**Comment by ErynManela** [comment]
Here's the whole test code:`
using System;
using System.Linq;
using System.Text;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.TestHost;
using Microsoft.AspNetCore.Hosting;
using Xunit;
using System.Net;
using NameValueHeaderValue = Microsoft.Net.Http.Headers.NameValueHeaderValue;
public class BasicAuthTest
    {
        
        private readonly TestServer _server;
        private readonly HttpClient _client;
        
        public BasicAuthTest()
        {
            // Arrange
            _server = new TestServer(new WebHostBuilder()
                .UseKestrel(options => { options.Listen(IPAddress.Loopback, 44300 ); })
                .UseStartup<Startup>());
            _client = _server.CreateClient();
        }

        [Fact]
        public async Task BasicAuthSucceeds()
        {
            var username = "username";
            var password = "password";
                
            // Act
            var request = new HttpRequestMessage()
            {
                RequestUri = new Uri("https://localhost:4430/"),
                Method = HttpMethod.Get    
            };
            request.Headers.Add("Scheme","https");
            string svcCredentials = Convert.ToBase64String(ASCIIEncoding.ASCII.GetBytes(username + ":" + password));

            request.Headers.Add("Authorization", "Basic " + svcCredentials);
            var response = await _client.SendAsync(request);
            response.EnsureSuccessStatusCode();
        }
        
        [Fact]
        public async Task IncorrectAuthFails()
        {
            var username = "foo";
            var password = "INVALIDPASSWORD";
                
            // Act
            var request = new HttpRequestMessage()
            {
                RequestUri = new Uri("https://localhost:4430/"),
                Method = HttpMethod.Get    
            };
            request.Headers.Add("Scheme","https");
            string svcCredentials = Convert.ToBase64String(ASCIIEncoding.ASCII.GetBytes(username + ":" + password));

            request.Headers.Add("Authorization", "Basic " + svcCredentials);
            var response = await _client.SendAsync(request);
            var wwwAuth = response.Headers.WwwAuthenticate.Single();
            var nvh = NameValueHeaderValue.Parse(wwwAuth.Parameter);
            //fails
            Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode);
            Assert.Equal("Basic", wwwAuth.Scheme);
            Assert.Equal("realm", nvh.Name);

        }
}`

**Comment by msmolka** [comment]
Are you sure you have ports right?
On server you have port 44300 
On URI you have 4430

One 0 less

**Comment by msmolka** [comment]
@aaronmanela could you put startup as well? Or whole test project then I can investigate

**Comment by ErynManela** [comment]
I figured it out - It was the kestrel https config that wasn't configured correctly, so I got rid of https for the purposes of testing my implementation. Thanks for getting me on the right path.
