### ISSUE TITLE
Provide a body in JSON format

### ISSUE THREAD

**Issue by robertmircea** [msmolka/ZNetCS.AspNetCore.Authentication.Basic#7]
Is it possible to provide a body (in JSON format if Accept header is application/json) when basic authentication fails? I am developing APIs and I am interested to return an error object  consistent with the rest of the the application errors from range 4xx.  For example, I would return:

```
HTTP/1.1 401 Unauthorized
Server: Kestrel
WWW-Authenticate: Basic realm="my realm"

{
        "errorCode": "failedCredentials",
        "message": "Client credentials validation failed "
}

**Comment by msmolka** [comment]
It is not possible out of box.
But you could try override `BasicAuthenticationHandler` and then method:

```c#
protected override Task HandleChallengeAsync(AuthenticationProperties context)
```

and register handler a bit differently. Instead of `.AddBasicAuthentication` use generic:
 
```c#
.AddScheme<BasicAuthenticationOptions, YourNewBasicAuthenticationHandler>(authenticationScheme, configureOptions)
```

**Comment by robertmircea** [comment]
Great! Thank you! It worked flawlessly.
